sonar.projectKey=fit-hub-backend
sonar.organization=tewaripiyush43
sonar.projectName=FitHub Backend

sonar.sources=.

# 3. Exclusions (don't scan external node modules or test artifacts)
sonar.exclusions=node_modules/**,coverage/**

# 4. Encoding
sonar.sourceEncoding=UTF-8
